CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE typing_test
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    speed      INTEGER                                 NOT NULL,
    accuracy   DOUBLE PRECISION                        NOT NULL,
    errors     INTEGER                                 NOT NULL,
    score      DOUBLE PRECISION                        NOT NULL,
    user_id    BIGINT,
    text_id    BIGINT,
    CONSTRAINT pk_typing_test PRIMARY KEY (id)
);

CREATE TABLE typing_text
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    content    VARCHAR(255),
    difficulty VARCHAR(255),
    language   VARCHAR(255),
    CONSTRAINT pk_typingtext PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    username    VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    total_score DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id  BIGINT NOT NULL,
    roles_id BIGINT NOT NULL
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE typing_test
    ADD CONSTRAINT FK_TYPING_TEST_ON_TEXT FOREIGN KEY (text_id) REFERENCES typing_text (id);

ALTER TABLE typing_test
    ADD CONSTRAINT FK_TYPING_TEST_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (roles_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);